name: Increment Version
on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Type of version bump'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  increment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Perform Version Bump
        run: |
          chmod +x .github/scripts/*
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "git@github.com:"

          # Calls your version script with 'major' or 'minor'
          .github/scripts/version.sh ${{ github.event.inputs.bump_type }}
